INSERT INTO `school` (`SchoolID`, `SchoolNaam`) VALUES
(1, 'ABC Hogeschool\r\n'),
(2, 'Academie Artemis Hogeschool voor Styling\r\n'),
(3, 'Academie voor Wetgeving\r\n'),
(4, 'Aeres Hogeschool\r\n'),
(5, 'Amsterdam School of Real Estate\r\n'),
(6, 'Amsterdamse Hogeschool voor de Kunsten\r\n'),
(7, 'ArtEZ hogeschool voor de kunsten\r\n'),
(8, 'Avans Hogeschool\r\n'),
(9, 'Avans+\r\n'),
(10, 'Business School Nederland\r\n'),
(11, 'Capabel Hogeschool\r\n'),
(12, 'Centrum voor Humanistische VormingÃƒâ€šÃ‚\r\n'),
(13, 'Christelijke Hogeschool Ede\r\n'),
(14, 'Codarts Hogeschool voor de Kunsten\r\n'),
(15, 'Cursus Godsdienst Onderwijs\r\n'),
(16, 'De Haagse Hogeschool\r\n'),
(17, 'Design Academy Eindhoven\r\n'),
(18, 'Driestar Hogeschool\r\n'),
(19, 'EuroCollege University of Applied Sciences\r\n'),
(20, 'European Institute For Brand Management\r\n'),
(21, 'Fontys Hogescholen\r\n'),
(22, 'Fotovakschool\r\n'),
(23, 'Gerrit Rietveld Academie\r\n'),
(24, 'Hanzehogeschool Groningen\r\n'),
(25, 'HAS Hogeschool\r\n'),
(26, 'HBO Da Vinci Drechtsteden\r\n'),
(27, 'HKU\r\n'),
(28, 'Hogeschool De Kempel\r\n'),
(29, 'Hogeschool der Kunsten Den Haag\r\n'),
(30, 'Hogeschool Dirksen\r\n'),
(31, 'Hogeschool E3\r\n'),
(32, 'Hogeschool Inholland\r\n'),
(33, 'Hogeschool iPabo\r\n'),
(34, 'Hogeschool ISBW\r\n'),
(35, 'Hogeschool Leiden\r\n'),
(36, 'Hogeschool NCOI\r\n'),
(37, 'Hogeschool NIFA\r\n'),
(38, 'Hogeschool Notenboom\r\n'),
(39, 'Hogeschool NOVI\r\n'),
(40, 'Hogeschool PBNA\r\n'),
(41, 'Hogeschool Rotterdam\r\n'),
(42, 'Hogeschool Schoevers\r\n'),
(43, 'Hogeschool SDO\r\n'),
(44, 'Hogeschool Tio\r\n'),
(45, 'Hogeschool Utrecht\r\n'),
(46, 'Hogeschool van Amsterdam\r\n'),
(47, 'Hogeschool van Arnhem en Nijmegen\r\n'),
(48, 'Hogeschool voor Pedagogisch en Sociaal-Agogisch On'),
(49, 'Hogeschool West-Nederland voor Vertaler en Tolk\r\n'),
(50, 'Hotelschool The Hague\r\n'),
(51, 'HZ University of Applied Sciences\r\n'),
(52, 'Instituut Defensie Leergangen\r\n'),
(53, 'Inter College Business School\r\n'),
(54, 'Iselinge Hogeschool\r\n'),
(55, 'Islamitische Universiteit Europa\r\n'),
(56, 'Islamitische Universiteit Rotterdam\r\n'),
(57, 'ITV Hogeschool voor Tolken en Vertalen\r\n'),
(58, 'IVA Driebergen Business School\r\n'),
(59, 'Katholieke Pabo Zwolle\r\n'),
(60, 'Koninklijk Actuarieel Genootschap & Actuarieel Ins'),
(61, 'LOI Hogeschool\r\n'),
(62, 'Markus Verbeek Praehep\r\n'),
(63, 'Marnix Academie\r\n'),
(64, 'NCOI / Pro Education\r\n'),
(65, 'Nederlandse Loodsencorporatie\r\n'),
(66, 'Nederlandse School voor Onderwijs Management\r\n'),
(67, 'Netherlands Business Academy\r\n'),
(68, 'Netherlands Maritime University\r\n'),
(69, 'NHA\r\n'),
(70, 'NHL Hogeschool\r\n'),
(71, 'NHTV internationaal hoger onderwijs Breda\r\n'),
(72, 'NTI\r\n'),
(73, 'Nyenrode New Business School\r\n'),
(74, 'Opleidingsinstelling Geestelijke Gezondheidszorg V'),
(75, 'Oysterwyck Hogeschool\r\n'),
(76, 'Philipse Business School\r\n'),
(77, 'Register Belastingadviseurs\r\n'),
(78, 'Saxion\r\n'),
(79, 'Saxion Next\r\n'),
(80, 'Schouten & Nelissen University\r\n'),
(81, 'SOD Next\r\n'),
(82, 'SOMT\r\n'),
(83, 'Stenden Hogeschool\r\n'),
(84, 'Stenden Masters\r\n'),
(85, 'Team Academy\r\n'),
(86, 'The New School for Information Services\r\n'),
(87, 'THIM Hogeschool voor Fysiotherapie\r\n'),
(88, 'Thomas More Hogeschool\r\n'),
(89, 'TMO Fashion Business School\r\n'),
(90, 'Tyndale Theological Seminary\r\n'),
(91, 'Van Hall Larenstein\r\n'),
(92, 'Viaa\r\n'),
(93, 'Wagner Group\r\n'),
(94, 'Webster University\r\n'),
(95, 'Windesheim\r\n'),
(96, 'Wittenborg University of Applied Sciences\r\n'),
(97, 'Zuyd Hogeschool\r\n');
